import 'server-only';

import {
  AlignmentType,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from 'docx';

import type { GeneratedReport } from './types';
import { formatCurrency, formatDisplayDate, normalizeSlug } from './utils';

function formatMetricValue(value: number) {
  return Number.isInteger(value) ? String(value) : value.toFixed(2);
}

function metricChangeLabel(changePercent: number | null) {
  if (changePercent === null) {
    return 'No prior period comparison';
  }

  return `${changePercent >= 0 ? '+' : ''}${changePercent.toFixed(1)}% vs previous period`;
}

export function buildGeneratedReportFilename(report: GeneratedReport) {
  return `${normalizeSlug(report.dataSnapshot.departmentName)}-${report.periodType}-${report.periodStart}-to-${report.periodEnd}`;
}

export async function buildGeneratedReportDocx(report: GeneratedReport) {
  const snapshot = report.dataSnapshot;
  const metricRows = snapshot.totals.map(
    (metric) =>
      new TableRow({
        children: [
          new TableCell({ children: [new Paragraph(metric.label)] }),
          new TableCell({ children: [new Paragraph(formatMetricValue(metric.total))] }),
          new TableCell({ children: [new Paragraph(formatMetricValue(metric.previousTotal))] }),
          new TableCell({ children: [new Paragraph(metricChangeLabel(metric.changePercent))] }),
        ],
      })
  );

  const handlerRows = snapshot.handlerSummary.map(
    (handler) =>
      new TableRow({
        children: [
          new TableCell({ children: [new Paragraph(handler.handledByName)] }),
          new TableCell({ children: [new Paragraph(String(handler.weeksHandled))] }),
          new TableCell({ children: [new Paragraph(String(handler.totalVisitors))] }),
        ],
      })
  );

  const document = new Document({
    sections: [
      {
        children: [
          new Paragraph({
            text: 'Christhood Accountability Platform',
            heading: HeadingLevel.TITLE,
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({
            children: [
              new TextRun({ text: `${snapshot.departmentName} Executive Report`, bold: true }),
            ],
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({
            text: `${formatDisplayDate(report.periodStart)} to ${formatDisplayDate(report.periodEnd)}`,
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({
            text: `Generated by ${report.generatedByName || 'CAP leadership workflow'}`,
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({
            text: `Comparison window: ${formatDisplayDate(snapshot.previousPeriodStart)} to ${formatDisplayDate(snapshot.previousPeriodEnd)}`,
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({ text: '' }),
          new Paragraph({
            text: 'Executive Summary',
            heading: HeadingLevel.HEADING_1,
          }),
          ...report.summaryText
            .split(/\n{2,}/)
            .filter(Boolean)
            .map(
              (block) =>
                new Paragraph({
                  children: [new TextRun(block.trim())],
                  spacing: { after: 220 },
                })
            ),
          new Paragraph({
            text: 'Operational Snapshot',
            heading: HeadingLevel.HEADING_1,
          }),
          new Paragraph(`Reporting weeks: ${snapshot.recordCount}`),
          new Paragraph(`Visitors: ${snapshot.totalVisitors}`),
          new Paragraph(`Anomaly flags: ${snapshot.anomalyCount}`),
          ...(snapshot.netPosition
            ? [new Paragraph(`Net position: ${formatCurrency(snapshot.netPosition.total)}`)]
            : []),
          new Paragraph({
            text: 'Metric Totals',
            heading: HeadingLevel.HEADING_1,
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  new TableCell({ children: [new Paragraph('Metric')] }),
                  new TableCell({ children: [new Paragraph('Current')] }),
                  new TableCell({ children: [new Paragraph('Previous')] }),
                  new TableCell({ children: [new Paragraph('Change')] }),
                ],
              }),
              ...metricRows,
            ],
          }),
          new Paragraph({ text: '' }),
          new Paragraph({
            text: 'Handler Accountability',
            heading: HeadingLevel.HEADING_1,
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  new TableCell({ children: [new Paragraph('Handler')] }),
                  new TableCell({ children: [new Paragraph('Weeks')] }),
                  new TableCell({ children: [new Paragraph('Visitors')] }),
                ],
              }),
              ...handlerRows,
            ],
          }),
          ...(snapshot.anomalyFields.length > 0
            ? [
                new Paragraph({ text: '' }),
                new Paragraph({
                  text: 'Anomaly Watch',
                  heading: HeadingLevel.HEADING_1,
                }),
                new Paragraph(snapshot.anomalyFields.join(', ')),
              ]
            : []),
        ],
      },
    ],
  });

  return Packer.toBuffer(document);
}
