import Link from 'next/link';
import { notFound } from 'next/navigation';

import { PrintReportButton } from '@/components/cap/print-report-button';
import { getSession } from '@/lib/cap/auth';
import { getGeneratedReportById } from '@/lib/cap/services';
import { formatCurrency, formatDisplayDate } from '@/lib/cap/utils';

function formatMetricValue(value: number) {
  return Number.isInteger(value) ? String(value) : value.toFixed(2);
}

export default async function GeneratedReportPrintPage({
  params,
}: {
  params: Promise<{ reportId: string }>;
}) {
  const session = await getSession();
  const { reportId } = await params;
  const numericReportId = Number(reportId);

  if (!Number.isFinite(numericReportId) || numericReportId <= 0) {
    notFound();
  }

  let report;
  try {
    report = await getGeneratedReportById(session!.user, numericReportId);
  } catch {
    notFound();
  }

  const snapshot = report.dataSnapshot;

  return (
    <section className="mx-auto max-w-5xl space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-3 rounded-[28px] border border-[#ddd3f0] bg-white p-6 shadow-sm print:hidden">
        <div>
          <p className="text-xs font-semibold uppercase tracking-[0.3em] text-[#C9A461]">Report export</p>
          <h2 className="mt-2 text-3xl font-semibold text-[#241c33]">{snapshot.departmentName} executive report</h2>
          <p className="mt-2 text-sm text-[#5f5673]">
            Use your browser print dialog to save this page as PDF, or download the DOCX copy.
          </p>
        </div>
        <div className="flex flex-wrap gap-3">
          <a
            href={`/api/reports/${report.id}/docx`}
            className="rounded-2xl bg-[#4B248C] px-4 py-2 text-sm font-semibold text-white"
          >
            Download DOCX
          </a>
          <PrintReportButton />
          <Link
            href={`/insights?departmentId=${report.departmentId}`}
            className="rounded-2xl border border-[#d9cfee] px-4 py-2 text-sm font-semibold text-[#241c33]"
          >
            Back to Insights
          </Link>
        </div>
      </div>

      <article className="rounded-[32px] border border-[#ddd3f0] bg-white p-8 shadow-sm print:border-0 print:shadow-none">
        <header className="border-b border-[#eee5fa] pb-6">
          <p className="text-xs font-semibold uppercase tracking-[0.3em] text-[#C9A461]">
            CIOM Portal
          </p>
          <h1 className="mt-3 text-4xl font-semibold text-[#241c33]">{snapshot.departmentName} Executive Report</h1>
          <p className="mt-3 text-sm text-[#5f5673]">
            {formatDisplayDate(report.periodStart)} to {formatDisplayDate(report.periodEnd)} | Generated {report.generatedAt.slice(0, 10)}
          </p>
          <p className="mt-2 text-sm text-[#5f5673]">
            Generated by {report.generatedByName || 'CIOM Portal leadership workflow'} | Comparison window{' '}
            {formatDisplayDate(snapshot.previousPeriodStart)} to {formatDisplayDate(snapshot.previousPeriodEnd)}
          </p>
        </header>

        <div className="mt-8 grid gap-4 md:grid-cols-4">
          <div className="rounded-3xl bg-[#fbf9fe] p-5">
            <p className="text-xs uppercase tracking-[0.2em] text-[#8a7ca7]">Records</p>
            <p className="mt-2 text-3xl font-semibold text-[#241c33]">{snapshot.recordCount}</p>
          </div>
          <div className="rounded-3xl bg-[#fbf9fe] p-5">
            <p className="text-xs uppercase tracking-[0.2em] text-[#8a7ca7]">Visitors</p>
            <p className="mt-2 text-3xl font-semibold text-[#241c33]">{snapshot.totalVisitors}</p>
          </div>
          <div className="rounded-3xl bg-[#fbf9fe] p-5">
            <p className="text-xs uppercase tracking-[0.2em] text-[#8a7ca7]">Anomalies</p>
            <p className="mt-2 text-3xl font-semibold text-[#241c33]">{snapshot.anomalyCount}</p>
          </div>
          <div className="rounded-3xl bg-[#fbf9fe] p-5">
            <p className="text-xs uppercase tracking-[0.2em] text-[#8a7ca7]">Net Position</p>
            <p className="mt-2 text-3xl font-semibold text-[#241c33]">
              {snapshot.netPosition ? formatCurrency(snapshot.netPosition.total) : 'N/A'}
            </p>
          </div>
        </div>

        <section className="mt-8">
          <h2 className="text-2xl font-semibold text-[#241c33]">Executive Summary</h2>
          <div className="mt-4 rounded-3xl bg-[#fffaf0] p-6">
            <p className="whitespace-pre-wrap text-sm leading-8 text-[#3d3452]">{report.summaryText}</p>
          </div>
        </section>

        <section className="mt-8">
          <h2 className="text-2xl font-semibold text-[#241c33]">Metric Totals</h2>
          <div className="mt-4 grid gap-4 md:grid-cols-2">
            {snapshot.totals.map((metric) => (
              <div key={metric.fieldKey} className="rounded-3xl border border-[#efe5c5] bg-[#fffdfa] p-5">
                <p className="text-sm font-semibold text-[#241c33]">{metric.label}</p>
                <p className="mt-2 text-2xl font-semibold text-[#241c33]">{formatMetricValue(metric.total)}</p>
                <p className="mt-2 text-sm text-[#5f5673]">Previous: {formatMetricValue(metric.previousTotal)}</p>
                <p className="mt-1 text-xs uppercase tracking-[0.2em] text-[#8a7ca7]">
                  {metric.changePercent === null
                    ? 'No prior comparison'
                    : `${metric.changePercent >= 0 ? '+' : ''}${metric.changePercent.toFixed(1)}% vs previous period`}
                </p>
              </div>
            ))}
          </div>
        </section>

        <section className="mt-8">
          <h2 className="text-2xl font-semibold text-[#241c33]">Handler Accountability</h2>
          <div className="mt-4 overflow-x-auto rounded-3xl border border-[#e6def4]">
            <table className="min-w-full divide-y divide-[#ece4f8] text-sm">
              <thead className="bg-[#fbf9fe] text-left text-[#5f5673]">
                <tr>
                  <th className="px-4 py-3">Handler</th>
                  <th className="px-4 py-3">Weeks</th>
                  <th className="px-4 py-3">Visitors</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#f3eefb]">
                {snapshot.handlerSummary.map((handler) => (
                  <tr key={handler.handledByUserId}>
                    <td className="px-4 py-3 font-medium text-[#241c33]">{handler.handledByName}</td>
                    <td className="px-4 py-3 text-[#5f5673]">{handler.weeksHandled}</td>
                    <td className="px-4 py-3 text-[#5f5673]">{handler.totalVisitors}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>
      </article>
    </section>
  );
}
